name: Release

on:
  push:
    tags:
      - '*'

jobs:
  release:
    if: startsWith(github.ref, 'refs/tags/')
    runs-on: ubuntu-latest
    steps:
      - name: Build Changelog
        id: build_changelog
        uses: mikepenz/release-changelog-builder-action@v2.9.0
        with:
          failOnError: true
          commitMode: true
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Create Release
        uses: actions/create-release@v1
        with:
          tag_name: ${{ github.ref }}
          release_name: ${{ github.ref }}
          body: ${{steps.build_changelog.outputs.changelog}}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - uses: actions/checkout@v1

      # Build
      - name: Build the file
        run: |
          cd /home/runner/work/custom-sonos-card/custom-sonos-card
          npm install
          npm run build

      - name: Upload to release
        uses: svenstaro/upload-release-action@v1-release

        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          file: /home/runner/work/custom-sonos-card/custom-sonos-card/dist/custom-sonos-card.js
          asset_name: custom-sonos-card.js
          tag: ${{ github.ref }}
          overwrite: true